function toggleAudio(){const m=document.getElementById("bgMusic"),b=document.getElementById("navMusicBtn");if(!m)return;if(m.paused)m.play().then(()=>b.innerHTML="⏸ Pause").catch(console.log);else{m.pause();b.innerHTML="♫ Music"}}
let pageHistoryArray=["welcome"];function hideAllPages(){["welcome","passwordPage","envelopePage","letterPage","chapter2","chapter3","finalChapter","birthdayReveal","celebrationScene","ultimateEnding"].forEach(id=>{let p=document.getElementById(id);if(p){p.classList.add("hidden");p.style.display="none"}})}
function showPage(id){clearTimers();hideAllPages();let p=document.getElementById(id);if(p){p.classList.remove("hidden");p.style.display="flex"}if(pageHistoryArray.at(-1)!==id)pageHistoryArray.push(id);document.getElementById("navBackBtn").style.display=pageHistoryArray.length>1?"inline-flex":"none"}
function goBackPage(){if(pageHistoryArray.length>1){pageHistoryArray.pop();showPage(pageHistoryArray.pop());pageHistoryArray.push(document.querySelector(".page:not(.hidden),#welcome")?.id||"welcome")}}
function clearTimers(){if(window.timers)window.timers.forEach(clearInterval);window.timers=[]}
function nextPage(){showPage("passwordPage")}function checkPassword(){let i=document.getElementById("password");if(i.value.toLowerCase().trim()==="favourite chapter")showPage("envelopePage");else{ i.classList.add("wrong");setTimeout(()=>i.classList.remove("wrong"),500);alert("Wrong Password 💔")}}
function openEnvelope(){showPage("letterPage");document.getElementById("nextChapterBtn").style.display="none";startLetter()}
const lines=["Hey tui... ❤️","Haa... tokei bolchi. 😊","Hoyto vabchis...","Eta sudhu ekta website... na","Eta amar tor jonno banano ekta chotto surprise. 🤍","So aste aste por...","Golpota ekhono shesh hoyni... ✨"];let line=0;
function startLetter(){line=0;document.getElementById("typewriter").innerHTML="";showNextLine()}function showNextLine(){if(line>=lines.length){setTimeout(()=>document.getElementById("nextChapterBtn").style.display="block",500);return}typeText(document.getElementById("typewriter"),lines[line],()=>{document.getElementById("typewriter").innerHTML+="<br><br>";line++;setTimeout(showNextLine,700)})}
function typeText(box,text,done){let i=0;let t=setInterval(()=>{box.innerHTML+=text.charAt(i++);if(i>=text.length){clearInterval(t);done()}},35);timers.push(t)}
function goToChapter2(){showPage("chapter2");startChapter2()}
const chapter2Lines=["Our story didn't really start with a beautiful moment... 🤍","বরং শুরুটা হয়েছিল একটা classroom-এ... আর একটা ছোট্ট ঝগড়া দিয়ে। 😬","সেদিন কে জানত, ওই মানুষটার সাথেই একদিন এত কথা জমে থাকবে... এত memories তৈরি হবে।","At that time, we weren't even close... সত্যি বলতে, friend বললেও হয়তো একটু বেশি বলা হয়ে যেত।","Then came 28 November 2023... ✨","একটা simple video-তে তোর একটা comment... আর somehow, সেখান থেকেই আবার আমাদের কথা শুরু হলো।","কথা বলতে বলতে একসময় তুই আমাকে তোর number দিতে চাইলি।","But TikTok-এর privacy তখন আমাদের একটু পরীক্ষা নিতে চেয়েছিল। 😭😂","তাই numberটা সরাসরি দেখাতে না পেরে তুই যেভাবে দিলি...",'"zero one seven" 😁',"সত্যি বলছি, তোর ওই বুদ্ধি দেখে আমি সেদিন একটু অবাকই হয়েছিলাম। 😂❤️","তারপর... একটার পর একটা দিন চলে গেল।","কথা বাড়তে থাকল, রাতগুলো একটু একটু করে ছোট হতে থাকল... আর অজান্তেই তুই হয়ে উঠলি আমার পরিচিত মানুষগুলোর মধ্যে একটু আলাদা একজন।","But then... 27 April 2024. 💔","হঠাৎ করেই তুই হারিয়ে গেলি।","কোনো proper goodbye ছিল না... কোনো explanation-ও না।","আমি তোকে খুঁজেছি... কিন্তু কোথাও পেলাম না।","সময় চলে গেল। Days became months... আর আমি ভেবেছিলাম, হয়তো গল্পটা এখানেই শেষ।","But some stories don't end when we think they do...","Because then came 2 June 2025. ✨","একদিন হঠাৎ... an unknown number থেকে একটা message এলো।","আর message-এর ওপাশে ছিলি... তুই। ❤️","কী অদ্ভুত না? এতদিন পরেও somehow, we found our way back to each other.","তারপর থেকে আবার কথা... আবার সেই পরিচিত feeling... আর এবার গল্পটা আর হারিয়ে যায়নি।","Maybe that's what makes our story a little different...","কিছু মানুষ জীবনে আসে খুব quietly...","কিছুদিন থাকে... তারপর হারিয়ে যায়...","কিন্তু যদি তারা সত্যিই important হয়, somehow life তাদের আবার ফিরিয়ে আনে। 🤍","And maybe... that's exactly what happened with us.","কিন্তু জানিস তো... এই গল্পটা এখানেও শেষ হয়নি।","Because the best part of our story... is still being written. ❤️"];let c2=0;
function startChapter2(){c2=0;document.getElementById("chapter2Story").innerHTML="";showC2()}function showC2(){let box=document.getElementById("chapter2Story"),b=document.getElementById("chapter2NextBtn");if(c2>=chapter2Lines.length){b.textContent="Continue to Chapter 3 →";b.style.display="inline-flex";b.onclick=goToChapter3;return}document.getElementById("memoryNo").textContent=String(c2+1).padStart(2,"0");let text=chapter2Lines[c2];let cls=text.includes("28 November")?"dateMoment":text.includes("27 April")?"sadMoment":text.includes("2 June")?"returnMoment":"";box.innerHTML=`<div class="chapterStoryText ${cls}"></div>`;b.style.display="none";typeText(box.firstChild,text,()=>{c2++;b.textContent="Continue ✦";b.style.display="inline-flex";b.onclick=showC2})}
function goToChapter3(){showPage("chapter3");startChapter3()}const chapter3Lines=["At first, everything was pretty simple... 😊","আমি একটু বেশি fun করতাম, আর তুইও সেগুলো equally enjoy করতি।","তারপর কখন যে আমরা এতটা close হয়ে গেলাম... honestly, I didn't even notice. 🤍","কিছু রাত তো এমনও গেছে—9টা-10টায় কথা শুরু করে কখন যে সকাল 5টা-6টা বেজে গেছে, বুঝতেই পারিনি। 🌙","সবচেয়ে অবাক করার বিষয়... এতক্ষণ কথা বলার পরেও আমাদের কথা যেন কখনো শেষ হতো না।","আর তোর ওই জেদটা... 😑❤️","মাঝে মাঝে সত্যিই বিরক্ত করতি, but somehow... that stubborn little side of you became one of my favourite things. 😂","কিন্তু জানিস...","ঠিক কখন তুই আমার কাছে এতটা important হয়ে গেলি, সেটা আমি নিজেও বুঝতে পারিনি।","কোনো particular moment ছিল না... কোনো special day-ও না।","Maybe it happened somewhere between all those random talks, stupid jokes, little arguments and endless nights...","কখন যে 'তুই' শুধু একজন মানুষ না হয়ে আমার favourite person হয়ে গেলি... I just didn't notice. 🤍","And maybe... that's the part I never really said. ❤️"];let c3=0;
function startChapter3(){c3=0;document.getElementById("chapter3Story").innerHTML="";document.getElementById("chapter3NextBtn").style.display="none";showC3()}function showC3(){let box=document.getElementById("chapter3Story"),b=document.getElementById("chapter3NextBtn");if(c3>=chapter3Lines.length){b.textContent="Continue to Final Chapter →";b.style.display="inline-flex";b.onclick=goToFinalChapter;return}b.style.display="none";typeText(box,chapter3Lines[c3],()=>{c3++;b.textContent="Continue ✦";b.style.display="inline-flex";b.onclick=showC3})}
function goToFinalChapter(){showPage("finalChapter")}const birthdayLines=["আজকের দিনটা শুধু একটা date না... 🤍","আজ এমন একজন মানুষের birthday, যে somehow আমার গল্পের একটা very special part হয়ে গেছে। ❤️","তোর জন্য আমার একটাই wish—","তুই সবসময় হাসিস, happy থাকিস, আর তোর ছোট-বড় সব dream একদিন সত্যি হোক। ✨","আর জীবন তোকে যত দূরেই নিয়ে যাক... তোর এই সুন্দর হাসিটা যেন কখনো হারিয়ে না যায়। 🤍"];let bday=0;
function openFinalSurprise(){showPage("birthdayReveal");bday=0;document.getElementById("birthdayMessage").innerHTML="";document.getElementById("oneMoreBtn").style.display="none";showBday()}function showBday(){let box=document.getElementById("birthdayMessage"),b=document.getElementById("oneMoreBtn");if(bday>=birthdayLines.length){b.textContent="🎂 Let's Celebrate";b.style.display="inline-flex";b.onclick=goToCelebration;return}b.style.display="none";typeText(box,birthdayLines[bday],()=>{bday++;b.textContent="Continue ✨";b.style.display="inline-flex";b.onclick=showBday})}
function goToCelebration(){showPage("celebrationScene");document.getElementById("celebrationMessage").innerHTML="";document.getElementById("celebrationContinueBtn").style.display="none";document.getElementById("makeWishBtn").style.display="inline-flex";document.getElementById("celebrationConfetti").innerHTML=""}
function startCelebration(){document.getElementById("makeWishBtn").style.display="none";let m=document.getElementById("celebrationMessage"),c=document.getElementById("celebrationContinueBtn");m.innerHTML="<p>Close your eyes... 🤍<br><br>Make a wish. ✨</p>";createConfetti();setTimeout(()=>m.innerHTML="<p>And now... make it come true. ❤️</p>",2200);setTimeout(()=>c.style.display="inline-flex",4200)}
function createConfetti(){let x=document.getElementById("celebrationConfetti"),p=["✦","✧","♡","✿","⋆","♥"];x.innerHTML="";for(let i=0;i<40;i++){let s=document.createElement("span");s.textContent=p[Math.floor(Math.random()*p.length)];s.style.left=Math.random()*100+"%";s.style.animationDelay=Math.random()*2+"s";s.className="confettiPiece";x.appendChild(s)}}
function goToFinalMessage(){showPage("ultimateEnding");let box=document.getElementById("ultimateText");box.innerHTML="";let a=["I don't know what the future holds for us...","But I'm really glad that, somehow, our paths crossed again. 🤍","From a classroom argument to endless midnight conversations...","কী সুন্দর একটা little journey হয়ে গেছে, তাই না? ❤️","আর যদি আজ তোর জন্য একটা wish করতে পারতাম...","তাহলে চাইতাম, life তোকে ঠিক সেই happiness-টাই দিক, যেটা তুই unknowingly আমার জীবনে নিয়ে এসেছিস। 🤍","This whole little world you just walked through...","এটা শুধু একটা website ছিল না।","এটা ছিল আমার মনে জমে থাকা কিছু কথা... শুধু তোর জন্য। ❤️","21 August — তোর day, আর somehow এখন আমার কাছেও এই দিন টি special একটা দিন।","সবসময় happy থাকিস। হাসিস। আর নিজের মতোই থাকিস। 🤍","— From someone who's really glad you found your way back. ❤️"];let n=0;function next(){if(n>=a.length)return;let p=document.createElement("p");p.className="finalTypingLine";box.appendChild(p);p.scrollIntoView({behavior:"smooth",block:"center"});typeText(p,a[n],()=>{n++;setTimeout(next,900)})}setTimeout(next,700)}
let timers=[];window.addEventListener("load",()=>{pageHistoryArray=["welcome"];showPage("welcome")});
